### ISSUE TITLE
Broken protobuf packages identified in conda-forge badges

### ISSUE THREAD

**Issue by tpdownes** [conda-forge/protobuf-feedstock#181]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Broken protobuf releases are reported in automated PRs for libraries that use it. See, for example:

- https://github.com/conda-forge/google-cloud-life-sciences-feedstock/pull/15

As of today, the badges report 22.2 "upstream" and 21.2 within conda-forge. The correct answer for conda-forge is 4.21.12 and, arguably, 4.22.2 for upstream. This stems from how protobuf versions its repo as a whole differently from the various language implementations within it.

- https://protobuf.dev/news/2022-05-06/#python-updates

I realize the versioning scheme is probably a nightmare to automate so I'm not sure there's an answer to fix the upstream badge.

But the conda-forge packages are plainly incorrect. Repos are immutable, but it appears that marking the 21.2 releases as "broken" is insufficient for the conda-forge badge to ignore them:

- https://anaconda.org/conda-forge/protobuf/files?version=21.2

This ought to be resolved generally and for the protobuf package in particular.

### Installed packages

```shell
protobuf
```

### Environment info

```shell
active environment : default
    active env location : /Users/tpdownes/local/miniconda3/envs/default
            shell level : 1
       user config file : /Users/tpdownes/.condarc
 populated config files : /Users/tpdownes/local/miniconda3/.condarc
                          /Users/tpdownes/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=13.2.1=0
                          __unix=0=0
       base environment : /Users/tpdownes/local/miniconda3  (writable)
      conda av data dir : /Users/tpdownes/local/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/tpdownes/local/miniconda3/pkgs
                          /Users/tpdownes/.conda/pkgs
       envs directories : /Users/tpdownes/local/miniconda3/envs
                          /Users/tpdownes/.conda/envs
               platform : osx-64
             user-agent : conda/23.1.0 requests/2.28.2 CPython/3.10.9 Darwin/22.3.0 OSX/13.2.1
                UID:GID : 828971:89939
             netrc file : None
           offline mode : False
```

**Comment by xylar** [comment]
@tpdownes, I can definitely see why this is annoying but I don't think there's much we can do about it in the feedstock. Because of the rather strange versioning practices in the prorobuf repo, the bot will not pick up new releases with the python version prefixed with 4. It seems we really *must* use the 2x.x versioning for the bot in order to avoid having to manually perform every version update.

All I can really recommend is to ignore the badge when it comes to protobuf.

**Comment by h-vetinari** [comment]
Yeah, the badges are broken since some builds got automerged when protobuf changed their version scheme. We marked them as broken but as you say, the badge still reflects the "highest" known version.

To be honest, I don't consider it a big problem. It's cosmetic, not a usability question.

The only possible solutions I could think of would be to teach the infra not to count broken packages (that's probably anaconda-internal, and they have more pressing things to do), or outright deleting the packages (which is something conda-forge generally doesn't do).

**Comment by xylar** [comment]
@h-vetinari, ah, I forgot about that.  Yeah, I think that could also be the reason.  And I would tend to agree that fixing this isn't a high priority for us.

**Comment by jakirkham** [comment]
Would recommend filing [a conda/infra issue]( https://github.com/conda/infrastructure/issues/new?assignees=&labels=type%3A%3Abug&template=0_bug.yml ). The badge is derived from Anaconda.org's API and that is the support repo for Anaconda infra issues

**Comment by tpdownes** [comment]
Thanks @jakirkham, I will do that. I do appreciate that there are a series of problems here, arguably none of which are yours.
