### ISSUE TITLE
google.protobuf.compiler package missing from conda package

### ISSUE THREAD

**Issue by thisch** [conda-forge/protobuf-feedstock#40]
The `google.protobuf.compiler` package can't be imported in python modules, because there is no `google/protobuf/compiler` subdirectory in `site-packages`.

However, if I manually install the python package of protobuf from the git clone of the protobuf repo (`python setup.py install --cpp_implementation --single-version-externally-managed --record record.txt`
same as is used in the build recipe), the compiler directory in site-packages is created and the import of `google.protobuf.compiler` works.

**Comment by hajapy** [comment]
Interesting... from what I can tell the `compiler` and `util` packages are not present in the original source (as in they do not exist here: https://github.com/google/protobuf/tree/master/python/google/protobuf), but get created during the build, by the following lines:

https://github.com/google/protobuf/blob/master/python/setup.py#L96
https://github.com/google/protobuf/blob/master/python/setup.py#L133

It also seems this line here is responsible for creating `__init__.py` files if they are absent:
https://github.com/google/protobuf/blob/master/python/setup.py#L149

I can verify from the build logs that the `_pb2.py` files were created, for instance these lines show up:
```
...
Generating google/protobuf/compiler/plugin_pb2.py...
...
Generating google/protobuf/util/json_format_proto3_pb2.py...
```
However, it seems these are not getting copied. I suspect what is happening is that find_packages is run before these files packages are created and so they don't get marked for inclusion. 

We could probably make a patch to create those dirs and empty `__init__.py` files so that the compile and util packages get included. It might be better if those directories were present in the source to begin with though... (even if empty and awaiting auto-gen `_pb2.py` files).

**Comment by thisch** [comment]
Thx for having a closer look what is happening here!

**Comment by hajapy** [comment]
Closed by https://github.com/conda-forge/protobuf-feedstock/pull/42
